### ISSUE TITLE
Bug: GET /api/reports/preflight, POST /api/reports/generate and GET /api/reports/{id} return 404 — HTTP endpoints not implemented in backend

### ISSUE THREAD

**Issue by sbranham314** [strata-reports-ai/orchestrator-strata-reports#44]
## Bug description

The backend HTTP endpoints required by PR #5 (`GET /api/reports/preflight`, `POST /api/reports/generate`, `GET /api/reports/{id}`, `GET /api/reports`) all return **HTTP 404 — Not Found**. These routes are not registered in the deployed Azure Functions app.

The `ReportsFunction.cs` in `fn-strata-reports` only contains a **queue-triggered** worker (`[QueueTrigger("report-generate")]`) that processes narrative generation. None of the HTTP-triggered functions needed by the frontend UI were implemented in the backend.

## Failing tests

```bash
# Preflight check — returns 404 instead of 200 + { hasSomeData, missingTypes }
curl -s -w "\nHTTP_STATUS:%{http_code}" \
  "https://fn-strata-reports.azurewebsites.net/api/reports/preflight?propertyId=00000000-0000-0000-0000-000000000001&periodStart=2026-01-01&periodEnd=2026-03-31"
# Actual: HTTP_STATUS:404
# Expected: HTTP 200 with { "hasSomeData": bool, "missingTypes": string[] }

# Generate report — returns 404 instead of 202 + { reportId }
curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST \
  "https://fn-strata-reports.azurewebsites.net/api/reports/generate" \
  -H "Content-Type: application/json" \
  --data-raw '{"propertyId":"00000000-0000-0000-0000-000000000001","type":"quarterly","periodStart":"2026-01-01","periodEnd":"2026-03-31"}'
# Actual: HTTP_STATUS:404
# Expected: HTTP 202 with { "reportId": "<guid>" }

# Get report by ID (polling) — returns 404 instead of 200 + Report object
curl -s -w "\nHTTP_STATUS:%{http_code}" \
  "https://fn-strata-reports.azurewebsites.net/api/reports/00000000-0000-0000-0000-000000000001"
# Actual: HTTP_STATUS:404
# Expected: HTTP 200 with Report object { id, status, ... } or 401 if unauthenticated

# List reports — returns 404
curl -s -w "\nHTTP_STATUS:%{http_code}" \
  "https://fn-strata-reports.azurewebsites.net/api/reports"
# Actual: HTTP_STATUS:404
# Expected: HTTP 200 or 401
```

## Impact

The entire Generate Report UI flow introduced in PR #5 is broken end-to-end:
- The property autocomplete preflight check cannot run
- The Generate button cannot submit a report (even if form is filled)
- The polling progress stepper receives no data
- The reports list page has no data source

## Context

Related to: strata-reports-ai/orchestrator-strata-reports#30
Deployed PR: https://github.com/strata-reports-ai/web-strata-reports/pull/5

## Technical notes

**Missing backend functions** in `fn-strata-reports/Functions/ReportsFunction.cs` (or a new `ReportsHttpFunction.cs`):

1. `GET /api/reports/preflight?propertyId=&periodStart=&periodEnd=` — Check revenue/expense/task/review/inspection tables for the given property+period; return `{ hasSomeData: bool, missingTypes: string[] }`
2. `POST /api/reports/generate` — Accept `{ propertyId, type, periodStart, periodEnd, customNote? }`; create a Report row (status=`queued`), enqueue to `report-generate` queue, return HTTP 202 `{ reportId }`; return HTTP 409 if a non-failed report already exists for same (property, type, period)
3. `GET /api/reports/{id}` — Return Report row by ID (used for polling every 3s); must respect tenant RLS
4. `GET /api/reports` — Return list of reports for the authenticated tenant

All must be protected by `TenantMiddleware` (require valid `access_token` cookie).

**Comment by sbranham314** [comment]
Still failing after PR #7.
Failing test:
```bash
curl -s -w "\nHTTP_STATUS:%{http_code}" \
  "https://fn-strata-reports.azurewebsites.net/api/reports"
# Actual: HTTP_STATUS:404 (empty body)
# Expected: HTTP 200 with Report[] or HTTP 401 if unauthenticated
```
Note: PR #7 was a frontend-only fix (ReportsPage.tsx) and does not implement the backend endpoints. The `GET /api/reports` (and preflight/generate/get-by-id) endpoints remain unimplemented in `fn-strata-reports/Functions/ReportsFunction.cs` — only a QueueTrigger exists, no HTTP triggers.

**Comment by sbranham314** [comment]
Still failing after PR #14.

**Update**: `POST /api/reports/generate` now returns HTTP **500** (empty response body) instead of the previously-reported 404. The endpoint appears to have been implemented in the backend but is crashing before returning a response.

Failing test:
```bash
curl -s -b /tmp/cookies.txt -o /tmp/out.txt -w "%{http_code}" -X POST \
  "https://fn-strata-reports.azurewebsites.net/api/reports/generate" \
  -H "Content-Type: application/json" \
  -d '{"propertyId":"a247eded-1234-1234-1234-123456789abc","periodStart":"2026-01-01","periodEnd":"2026-03-31","reportType":"quarterly"}'
```
Actual: HTTP 500, empty response body
Expected: HTTP 404 (property not found) or HTTP 400/402

The 500 occurs with any body (valid or empty) when authenticated. Likely an unhandled exception in `ReportsFunction.Generate` — possibly in `IPlanEnforcementService.CheckReportGenerateAsync` or `IQueueService.EnqueueAsync`. Check Azure Function logs for the stack trace.

`GET /api/reports/{id}` and `GET /api/reports` still return 404 (not yet implemented).

**Comment by sbranham314** [comment]
Still failing after PR #7 (new failure mode — route conflict, not missing endpoint).

**Failing test:**
```bash
curl -s -b /tmp/cookies.txt -w "\nHTTP %{http_code}"   "https://fn-strata-reports.azurewebsites.net/api/reports/preflight?propertyId=1d29effb-1167-4e26-bb6f-bb3f084b530d&periodStart=2026-01-01&periodEnd=2026-03-31"
```
**Actual:** HTTP 400 — `{"type":"about:blank","title":"Bad Request","status":400,"detail":"id must be a valid UUID."}`
**Expected:** HTTP 200 with `{ hasSomeData: bool, missingTypes: string[] }`

**Root cause:** Azure Functions is matching `GET /api/reports/preflight` against the `reports/{id}` route (treating "preflight" as the `{id}` segment) instead of the literal `reports/preflight` route. The `ReportsPreflight` function exists in `Functions/ReportsFunction.cs:341` but is unreachable because the Azure Functions host resolves `reports/{id}` first.
